"""changes

Revision ID: 13e86cc8fb20
Revises: 6ae52c58299b
Create Date: 2024-03-13 15:54:55.062211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e86cc8fb20'
down_revision = '6ae52c58299b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('genre', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('genre')
        batch_op.drop_column('isbn')

    # ### end Alembic commands ###
